"""add checklists

Revision ID: 0959939afcb3
Revises: 18ecca93afdd
Create Date: 2025-06-08 13:09:51.468343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0959939afcb3'
down_revision: Union[str, None] = '18ecca93afdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_point', sa.Enum('start_shift', 'end_shift', name='checklisttimepoint'), nullable=False),
    sa.Column('check_list', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('time_point')
    )
    op.create_index(op.f('ix_check_lists_id'), 'check_lists', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_lists_id'), table_name='check_lists')
    op.drop_table('check_lists')
    # ### end Alembic commands ###
