"""debit

Revision ID: 10a1783e1ab6
Revises: b37a99cd17e0
Create Date: 2025-06-22 15:14:20.822677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a1783e1ab6'
down_revision: Union[str, None] = 'b37a99cd17e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('debit', sa.Boolean(), nullable=True))
    op.drop_column('orders', 'active')
    op.add_column('store_items', sa.Column('debit', sa.Boolean(), nullable=True))
    op.alter_column('store_items', 'supply_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('store_items', 'price_per_item',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_column('store_items', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_items', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('store_items', 'price_per_item',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('store_items', 'supply_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('store_items', 'debit')
    op.add_column('orders', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'debit')
    # ### end Alembic commands ###
