"""remove tags

Revision ID: 9fffc80babb5
Revises: 0959939afcb3
Create Date: 2025-06-10 17:32:02.525982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fffc80babb5'
down_revision: Union[str, None] = '0959939afcb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tags_id', table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_product_tag_id', table_name='product_tag')
    op.drop_table('product_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_tag',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_tag_product_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='product_tag_tag_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_tag_pkey')
    )
    op.create_index('ix_product_tag_id', 'product_tag', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tags_pkey'),
    sa.UniqueConstraint('name', name='tags_name_key')
    )
    op.create_index('ix_tags_id', 'tags', ['id'], unique=False)
    # ### end Alembic commands ###
