"""clients

Revision ID: a1a7af3e2870
Revises: f93e9d9c8bc1
Create Date: 2025-06-15 16:55:37.579629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a7af3e2870'
down_revision: Union[str, None] = 'f93e9d9c8bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('deactivated', sa.Boolean(), nullable=True))
    op.drop_column('clients', 'active')
    op.add_column('suppliers', sa.Column('deactivated', sa.Boolean(), nullable=True))
    op.drop_column('suppliers', 'active')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('suppliers', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('suppliers', 'deactivated')
    op.add_column('clients', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('clients', 'deactivated')
    # ### end Alembic commands ###
