"""discount

Revision ID: b37a99cd17e0
Revises: 855841e3b515
Create Date: 2025-06-15 19:15:30.954460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37a99cd17e0'
down_revision: Union[str, None] = '855841e3b515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('discount', sa.Numeric(precision=3, scale=0), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'discount')
    # ### end Alembic commands ###
