"""add shift to order

Revision ID: ce9d05de983d
Revises: c7c0204ab275
Create Date: 2025-04-21 21:24:55.892621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9d05de983d'
down_revision: Union[str, None] = 'c7c0204ab275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shift_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'shifts', ['shift_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'shift_id')
    # ### end Alembic commands ###
