"""user

Revision ID: f93e9d9c8bc1
Revises: 65a1f51180c7
Create Date: 2025-06-15 15:02:21.295482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f93e9d9c8bc1'
down_revision: Union[str, None] = '65a1f51180c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deactivated', sa.Boolean(), nullable=True))
    op.drop_column('users', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'deactivated')
    # ### end Alembic commands ###
