name: Deploy to Cloud Run

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SA_KEY }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: cafe-manager-api
          image: us-central1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/coffee-point-registry/coffee-point:latest
          region: us-central1
          allow_unauthenticated: true
          add_cloudsql_instances: ${{ secrets.INSTANCE_CONNECTION_NAME }}
          env_vars: |
            USE_CLOUD_SQL_PROXY=true
            INSTANCE_CONNECTION_NAME=${{ secrets.INSTANCE_CONNECTION_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASS=${{ secrets.DB_PASS }}
            DB_NAME=${{ secrets.DB_NAME }}
