name: Build and Push Docker Image

on:
#  push:
#    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker auth to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker

      - name: Build and Push image
        run: |
          docker build \
            --build-arg \
              DB_HOST=${{ secrets.DB_HOST }} \
              DB_USER=${{ secrets.DB_USER }} \
              DB_PASS=${{ secrets.DB_PASS }} \
              DB_NAME=${{ secrets.DB_NAME }} \
            -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/cafe-manager:latest \
            -f docker/Dockerfile .

          docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/cafe-manager:latest