name: Manage Cloud SQL

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Enable or Disable DB? (on/off)'
        required: true
        default: "off"
        type: choice
        options:
          - "on"
          - "off"

jobs:
  manage-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SA_KEY }}

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Install Cloud SQL component
        run: gcloud components install sql --quiet

      - name: Manage SQL Instance
        run: |
          INSTANCE="coffee-point-db"

          if [ "${{ github.event.inputs.action }}" == "on" ]; then
            echo "Enable DB..."
            POLICY="ALWAYS"
          elif [ "${{ github.event.inputs.action }}" == "off" ]; then
            echo "Disable DB..."
            POLICY="NEVER"
          fi

          gcloud sql instances patch "$INSTANCE" \
            --activation-policy="$POLICY" \
            --project="${{ secrets.GCLOUD_PROJECT_ID }}" \
            --quiet
